pandasの解答
Hiromu1612/BasicPython pull request #15
Opened 2024-03-31 13:20 UTC by Hiromu1612

2024-03-31 14:47 UTC, Tomoya-DataScience requested changes
.ipynbファイルが壊れているようなので，再提出をお願いします！

2024-03-31 14:47 UTC, Tomoya-DataScience commented on .vscode/launch.json
不要なファイルがaddされています

2024-03-31 14:47 UTC, Tomoya-DataScience commented on BasicPython-main/__pycache__/pi.cpython-312.pyc
不要なファイルがaddされています

2024-03-31 14:47 UTC, Tomoya-DataScience commented on BasicPython-main/california_housing_train.csv
不要なファイルがaddされています

2024-03-31 14:47 UTC, Tomoya-DataScience commented on BasicPython-main/euclid.py
不要なファイルがaddされています

2024-03-31 14:47 UTC, Tomoya-DataScience commented on BasicPython-main/machine_epsilon.py
不要なファイルがaddされています

2024-03-31 14:47 UTC, Tomoya-DataScience commented on BasicPython-main/matplotlib_exercise.ipynb
matplotlib課題のファイルでしょうか？

2024-03-31 14:47 UTC, Tomoya-DataScience commented on BasicPython-main/pandas_quiz.ipynb
ファイルが壊れていて見ることができませんね...
再度Githubからファイルをダウンロードしたものを解いて再提出をお願いします
![スクリーンショット (5443)](https://github.com/Hiromu1612/BasicPython/assets/92308219/0122cb62-5cd8-4835-a900-011cdf685758)

2024-03-31 14:47 UTC, Tomoya-DataScience commented on BasicPython-main/pi.py
不要なファイルがaddされています

2024-03-31 14:47 UTC, Tomoya-DataScience commented on BasicPython-main/prime__number.py
不要なファイルがaddされています

2024-03-31 14:47 UTC, Tomoya-DataScience commented on BasicPython-main/prime_number.py
不要なファイルがaddされています

2024-03-31 14:47 UTC, Tomoya-DataScience commented on BasicPython-main/quadratic_formula.py
不要なファイルがaddされています

2024-03-31 14:47 UTC, Tomoya-DataScience commented on BasicPython-main/trapezoidal_integral.py
不要なファイルがaddされています

2024-03-31 14:47 UTC, Tomoya-DataScience commented on README.md
不要なファイルがaddされています

2024-03-31 16:20 UTC, Hiromu1612 commented
ファイルを見れるように修正しました! 確認お願いします

2024-04-01 00:44 UTC, Tomoya-DataScience requested changes
🔴 が修正が必要な点， 🟢 がコメント（修正不要な点）です！

🟢問1
条件文と表示させる列が少し長いので以下のように
変数としてまとめると読みやすくなると思います！
また，reindexする必要はありません．

```
# 特定の条件を満たす行を選択するための条件式を定義
condition = (df_receipt['customer_id'] == "CS018205000001") & ((df_receipt['amount'] >= 1000) | (df_receipt['quantity'] >= 5))

# 表示させる列をcolumnsで指定
columns = ['sales_ymd', 'customer_id', 'product_cd', 'quantity', 'amount']

display(df_receipt.loc[condition, columns])
```


🔴問6

ほぼOKですが，これだと全ての行の欠損値が0埋めされてしまうので，
列名`amount`を指定して処理してください．
```
# 売上金額がない顧客の場合は0で埋める
df_merged["amount"] = df_merged["amount"].fillna(0)

# 先頭5件を表示
df_merged.head()
```

🔴問7

コードは正しいですが，`application_date`列の表示が誤っているので
再度実行したものを提出してください．

🟢問8

常用対数化した列の名前は`log_amount`などにする方が適切だと思います．

🟢問10, 11

データフレームは作成するだけなので表示する必要はありません．

2024-04-01 07:43 UTC, Tomoya-DataScience requested changes
🔴 が修正が必要な点， 🟢 がコメント（修正不要な点）です！

🟢問7

新しくDataFrameを作るより，単に
`df_customer[["customer_id", "application_date"]].head()`としてもいいと思いました．

🔴問8

コードと出力が対応していません．
2行目の`df_amount_log10 = df_amount.rename(columns={'log_10': 'df_amount_log10'})`は
`df_amount`の`log_10`列を`log_amount`に変更したかったのでしょうか？
（`df_amount`には`log_10 `列が存在しないため、実際には列名の変更は行われません ）
1行目の`df_amount`が少し長い気がするので，
`df_receipt_sum = df_receipt_only_member.groupby("customer_id").sum()[["amount"]]`
とすると読みやすくなると思います．
この`df_receipt_sum`の`amount`列に対して常用対数をとって
顧客ID，売上金額合計とともに表示すればOKです．

![image](https://github.com/Hiromu1612/BasicPython/assets/92308219/49519b20-1878-4d66-ad9c-123fd0554335)

2024-04-02 06:57 UTC, Hiromu1612 commented
問7,8の修正をしました。よろしくお願いします!

2024-04-02 07:05 UTC, Tomoya-DataScience approved these changes

2024-04-03 06:21 UTC, merged